### PR TITLE
Return booleans for device information where applicable

### LINKED ISSUE #21: Device::available() should return a boolean
Currently `Device::available()` returns a `cl_int` which is a bit confusing (I just had a bug where my logic was wrong due to that). I propose making it return a boolean. That is also what the OpenCL spec suggests: https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_DEVICE_AVAILABLE. That applies also to other `clGetDeviceInfo` calls, but the `CL_DEVICE_AVAILABLE` is the one I care most at the moment.

Ideally on the `opencl3` level it returns a Rust `bool` and not a `cl_bool`, which would again be harder to work with.

### PR DESCRIPTION
**Pull request by vmx**
If a `clGetDeviceInfo()` call returns a boolean value (cl_bool), return
it as a Rust `bool`.

Closes #21.

### CODE REVIEW

File: src/device.rs [hunk 1]
```diff
@@ -227,8 +227,8 @@ impl Device {
         Ok(get_device_info(self.id(), DeviceInfo::CL_DEVICE_IMAGE3D_MAX_DEPTH)?.to_size())
     }
 
-    pub fn image_support(&self) -> Result<cl_uint> {
-        Ok(get_device_info(self.id(), DeviceInfo::CL_DEVICE_IMAGE_SUPPORT)?.to_uint())
+    pub fn image_support(&self) -> Result<bool> {
+        Ok(get_device_info(self.id(), DeviceInfo::CL_DEVICE_IMAGE_SUPPORT)?.to_uint() == CL_TRUE)
```
Comment (kenba) [inline src/device.rs:231]: Originally in `C`, where integers were used to represent booleans: zero was `false` and *anything* else was `true`.
Although the calls should return `CL_TRUE` for true, they can only be relied on to return `CL_FALSE` for false.
Therefore the conversion should be `value != CL_FALSE`.

**Review by kenba — APPROVED** [review]
The conversions should be `!= CL_FALSE` not `==  CL_TRUE`.  
However, I'm going to approve this merge request and change the conversions after the merge.

**Comment by vmx** [comment]
Thanks @kenba, it totally makes sense, I shouldn't thought about this more deeply. I'm happy to adjust my code, so next time feel free to just leave the comment and I'll make the change (though it's of course appreciated that you fix it quickly :)
